# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden - Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- when: gitlab_runner_ssh_key|length == 0
  block:
    - name: "Create SSH key pair for communicating with Runners."
      community.crypto.openssh_keypair:
        path: "/etc/gitlab-runner/gitlab_runner_key"
        type: "ed25519"
      register: gitlab_runner_ssh_keypair

    - name: "Set SSH public key fact"
      ansible.builtin.set_fact:
        gitlab_runner_ssh_key: "{{ gitlab_runner_ssh_keypair.public_key }}"

- name: Download and install container-linux-config-transpiler
  ansible.builtin.get_url:
    url: "{{ gitlab_runner_transpiler_binary_url }}"
    dest: /usr/local/bin/ct
    mode: "0755"
    checksum: "{{ gitlab_runner_transpiler_binary_checksum }}"

- name: Place the container linux configuration on the host
  ansible.builtin.template:
    src: flatcar-linux-config.yml.j2
    dest: /etc/gitlab-runner/flatcar-linux-config.yml
    owner: root
    group: root
    mode: 0644
  notify:
    - "Transpile the flatcar linux configuration"

- name: "Check if ignition.json is available and create it in any case"
  ansible.builtin.stat:
    path: "/etc/gitlab-runner/ignition.json"
  register: ignition_exists
  changed_when: not ignition_exists.stat.exists
  notify:
    - "Transpile the flatcar linux configuration"

# This block is required to prepare for possible updates of the transpiler
# tool resulting in a different result. Also this helps to fix any kind of
# manual manipulation.
- name: "Check if ignition.json is up-to-date"
  when: ignition_exists.stat.exists
  block:
    - name: "Create temporary directory"
      ansible.builtin.tempfile:
        state: "directory"
        suffix: "ignition"
      register: temp_directory
      changed_when: false
      check_mode: no

    - name: "Dry-run of transpile the flatcar linux configuration"
      ansible.builtin.command: "ct -in-file /etc/gitlab-runner/flatcar-linux-config.yml -out-file {{ (temp_directory.path, 'ignition.json') | path_join }}"
      changed_when: false
      check_mode: no

    - name: "Stat temporary ignition.json file"
      ansible.builtin.stat:
        path: "{{ (temp_directory.path, 'ignition.json') | path_join }}"
      register: "temp_ignition_stats"
      changed_when:
        - temp_ignition_stats.stat.checksum != ignition_exists.stat.checksum
      check_mode: no
      notify:
        - "Transpile the flatcar linux configuration"

  always:
    - name: "Remove temporary directory"
      ansible.builtin.file:
        path: "{{ temp_directory.path }}"
        state: absent
      changed_when: false
      check_mode: no
