# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden - Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: Set OS family dependent variables
  include_vars: "{{ ansible_os_family|lower }}.yml"

- include: install.docker-machine.yml
  become: yes

- include: install.debianlike.yml
  become: yes
  when: ansible_os_family == "Debian"

- include: configuration.yml
  become: yes

...
