# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: Set concurrent limit value
  lineinfile:
    dest: "{{ tmp_runner_config_file.path }}"
    regexp: '^\s*limit =.*'
    line: '  limit = {{ gitlab_runner.limit | default(0) }}'
    state: present
    insertafter: '^\s*name ='
    backrefs: no
  check_mode: no
  notify:
    - Restart GitLab-Runner

...
