# SPDX-FileCopyrightText: 2022 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
name: CI
'on':
  pull_request:
  push:

env:
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1
  POETRY_VIRTUALENVS_PATH: ~/.cache/venv
  POETRY_CACHE_DIR: ~/.cache/poetry
  PIP_CACHE_DIR: ~/.cache/pip

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Prepare the job environment.
        uses: ./.github/workflows/prepare-action

      - name: Lint code.
        run: poetry run molecule lint

  license_compliance:
    name: Check license compliance with reuse.
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Prepare the job environment.
        uses: ./.github/workflows/prepare-action

      - name: Lint code.
        run: poetry run reuse lint

  test:
    name: Run Molecule tests.
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        distro:
          - ubuntu2004
          - debian10

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Prepare the job environment.
        uses: ./.github/workflows/prepare-action

      - name: Run Molecule tests.
        run: poetry run molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          REGISTRATION_TOKEN: ${{ secrets.registration_token }}
